server:
  port: 20003

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Colorful9767/config-repo.git
          force-pull: true
          search-paths: '{application}'
        # 属性重载
        overrides:
          test: mytest

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

############################################################
#
# eureka 服务注册中心配置
#
############################################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/
