server:
  port: 10002

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password:
  redis:
    database: 0
    host: centos
    port: 6379
    password: 123123
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#### actuator config
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
#        include: 'health,info'
  security:
    enabled: false


#### hystrix config
hystrix:
  command:
    default:  #  global config
      fallback:
        enabled: true
      ciruit-breaker:
        enabled: true
        error-threshold-precentage: 30
        request-volume-threshold: 5
        sleep-window-in-milliseconds: 10000
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            interrupt-on-timeout: true
            interrupt-on-cancel: true
            timeout-in-milliseconds: 10000
      metrics:
        rolling-stats:
          time-in-milliseconds: 20000  # time window
#          num-buckets: 10
#        rolling-percentile:
#          time-in-milliseconds: 20000
#          bucket-size: 300
    loginFail:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000  # override to global config