server:
  port: 32000
spring:
  application:
    name: feign-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

feign-client:
  ribbon:
    # 每台机器最大重试次数
    MaxAutoRetries: 2
    # 可以重试几台机器
    MaxAutoRetriesNextServer: 2
    # 连接超时时间
    ConnectTimeout: 1000
    # 业务处理超时时间
    ReadTimeout: 2000
    # 允许在所有HTTP METHOD进行重试
    OkToRetryOnAllOperations: true